scrape_configs:
  - job_name: "Spring boot app"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['backend:8080']
      # указан докер контейнер (backend), лучше указывать домен на котором находиться prometheus
      # host.docker.internal - приложение запущено локально, prometheus в контейнере
